version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: astrology-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: astrology_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - astrology-network

  # FastAPI Backend
  backend:
    build: .
    container_name: astrology-backend
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017
      - DATABASE_NAME=astrology_db
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - APP_NAME=Astrology Platform
      - DEBUG=False
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - astrology-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Interface (Optional - for development)
  web:
    image: nginx:alpine
    container_name: astrology-web
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - astrology-network

volumes:
  mongodb_data:

networks:
  astrology-network:
    driver: bridge
